### ISSUE TITLE
GPU not properly initializing, WhateverGreen not loading?

### ISSUE THREAD

**Issue by mfischl** [hacker1024/Dell-Inspiron-7586-Hackintosh#1]
I can not get pst the point of initializing the GPU, some additional info:

- OS installer is BigSur
- USB2 usb stick
- No modifications to the config except what is necessary by the guide (AppleXcpmCfgLock, generated device data, ...)
- Tried some bootflags for whatevergreen, but no success yet
- Charging sound works when plugging in
- Screen sleeps properly after some inactivity
- When plugging in external monitor, the internal one goes black and never returns

https://www.tonymacx86.com/attachments/img_20201124_185435-jpg.498158/
Start of conversation: https://www.tonymacx86.com/threads/dell-inspiron-7586-i7-8565u-intel-uhd-620.277104/page-15

**Comment by hacker1024** [comment]
If you try creating a config from scratch using the info in the README, do you get the same issue? I'm wondering if I stuffed something up before pushing.

**Comment by mfischl** [comment]
I will try that on the weekend, latest. Pumped to get this working 🚀

**Comment by merken** [comment]
> If you try creating a config from scratch using the info in the README, do you get the same issue? I'm wondering if I stuffed something up before pushing.

Hi, I have the same setup, I followed Dortania's guide to setup mine, I'll link my repo sometime today.

Details of my setup:
Dell Inspiron 7586 2 in 1
8th Generation Intel(R) Core(TM) [i7-8565U Processor](https://www.intel.com/content/www/us/en/products/processors/core/i7-processors/i7-8565u.html) (8MB Cache, up to 4.6 GHz)
Intel UHD 620 (device id 0x3EA0)
Intel Wireless 9560
NVIDIA GeForce MX150 2GB GDDR5 (not needed or either supported in macOS, will be disabled)
512GB M.2 PCIe NVMe Solid State Drive
15.6-inch UHD (3840 x 2160) 4K
originally had 16GBx1, DDR4, 2666MHz, **replaced with 2x** [Crucial 16 GB SODIMM DDR4-2400](https://www.crucial.com/memory/ddr4/ct16g4sfd824a)

**Comment by mfischl** [comment]
> > If you try creating a config from scratch using the info in the README, do you get the same issue? I'm wondering if I stuffed something up before pushing.
> 
> Hi, I have the same setup, I followed Dortania's guide to setup mine, I'll link my repo sometime today.
> 
> Details of my setup:
> Dell Inspiron 7586 2 in 1
> 8th Generation Intel(R) Core(TM) [i7-8565U Processor](https://www.intel.com/content/www/us/en/products/processors/core/i7-processors/i7-8565u.html) (8MB Cache, up to 4.6 GHz)
> Intel UHD 620 (device id 0x3EA0)
> Intel Wireless 9560
> NVIDIA GeForce MX150 2GB GDDR5 (not needed or either supported in macOS, will be disabled)
> 512GB M.2 PCIe NVMe Solid State Drive
> 15.6-inch UHD (3840 x 2160) 4K
> originally had 16GBx1, DDR4, 2666MHz, **replaced with 2x** [Crucial 16 GB SODIMM DDR4-2400](https://www.crucial.com/memory/ddr4/ct16g4sfd824a)

Is it working for you?

**Comment by merken** [comment]
> > > If you try creating a config from scratch using the info in the README, do you get the same issue? I'm wondering if I stuffed something up before pushing.
> > 
> > 
> > Hi, I have the same setup, I followed Dortania's guide to setup mine, I'll link my repo sometime today.
> > Details of my setup:
> > Dell Inspiron 7586 2 in 1
> > 8th Generation Intel(R) Core(TM) [i7-8565U Processor](https://www.intel.com/content/www/us/en/products/processors/core/i7-processors/i7-8565u.html) (8MB Cache, up to 4.6 GHz)
> > Intel UHD 620 (device id 0x3EA0)
> > Intel Wireless 9560
> > NVIDIA GeForce MX150 2GB GDDR5 (not needed or either supported in macOS, will be disabled)
> > 512GB M.2 PCIe NVMe Solid State Drive
> > 15.6-inch UHD (3840 x 2160) 4K
> > originally had 16GBx1, DDR4, 2666MHz, **replaced with 2x** [Crucial 16 GB SODIMM DDR4-2400](https://www.crucial.com/memory/ddr4/ct16g4sfd824a)
> 
> Is it working for you?

No, same result as you have... it goes pretty far, screen dims, then nothing until after some time the screen goes dark and can be turned on again after keyboard or touchpad interaction.

Unplugging and plugging the power supply triggers a chime through the speakers.
I can get Apple VoiceOver to start, sounding through the speakers, last thing it says is : YOU ARE CURRENTLY ON AN IMAGE in a robotic voice.

So yeah, pretty close

**Comment by merken** [comment]
Here's my repo:
https://github.com/merken/Inspiron7586

**Comment by merken** [comment]
Small question, the platform id and device id from this repo is
<key>AAPL,ig-platform-id</key>
<data>**CQClPg==**</data>
<key>AAPL,slot-name</key>
<string>Internal@0,2,0</string>
<key>device-id</key>
<data>**mz4AAA==**</data>


According to the Guide, it should be 
<img width="625" alt="image" src="https://user-images.githubusercontent.com/187081/100343245-672ac200-2fdf-11eb-8156-1b34f77083a7.png">

00009B3E for platform
9B3E0000 for device id

Are your values converted in some way?

**Comment by hacker1024** [comment]
Yes, they are stored in base64 form in the plist.
The ProperTree editor converts this for you.

**Comment by merken** [comment]
This is where I'm at with Big Sur:
![image](https://user-images.githubusercontent.com/187081/100351021-128d4400-2feb-11eb-86f8-bbe6d8cc5ec9.png)

**Comment by merken** [comment]
Ok, I'm done starting from scratch and I'm back at the point where it says that those two lines: start entered, displayed above.

I believe to have done everything correctly... Followed the guide. Screen dims at the end of those lines but no installer.

Do I need to re-create the installed from scratch? Format USB and repeat the process?

**Comment by mfischl** [comment]
> Ok, I'm done starting from scratch and I'm back at the point where it says that those two lines: start entered, displayed above.
> 
> I believe to have done everything correctly... Followed the guide. Screen dims at the end of those lines but no installer.
> 
> Do I need to re-create the installed from scratch? Format USB and repeat the process?

I checked you repo and saw that you switched to opencore 0.6 also? For me it yields the same results as before and for you, boot till that `ltlwm` wall and then slight screen dim and nothing. Has to be some whatevergreen config I guess.

**Comment by mfischl** [comment]
@merken I read a forum post which stated that removing `device-id` would at least let them see things and boot the installer (But later it would not let them have acceleration, fine). Doing that it seems like I get in a way different state. It goes past the sceenshot you posted, then, pressing keyboard keys would produce output along the lines that something is recognized as being pressed. Also there is infinite output of the wifi. I think its just the wifi scanning for access points. Maybe that helps you get along further.

**Comment by merken** [comment]
> @merken I read a forum post which stated that removing `device-id` would at least let them see things and boot the installer (But later it would not let them have acceleration, fine). Doing that it seems like I get in a way different state. It goes past the sceenshot you posted, then, pressing keyboard keys would produce output along the lines that something is recognized as being pressed. Also there is infinite output of the wifi. I think its just the wifi scanning for access points. Maybe that helps you get along further.

Thanks but leaving the device-id blank causes a kernel panic early on the boot.

I'm trying different configurations, but i seems this repo has thought out most of the issues, not sure what is causing the holdup...

I did get some progress by re-ordering the loading of the kexts, in the logs is shows that WhateverGreen.kext is being loaded successfully.

Now it loops on itlwm, seems to keep rescanning...

**Comment by merken** [comment]
Ok, progressing slowly, now I get **disk3 device is write locked** when trying to install Big Sur

**Comment by mfischl** [comment]
> Ok, progressing slowly, now I get **disk3 device is write locked** when trying to install Big Sur

Is that already with a GUI spinned up? Or still not past the verbose? Also can you push your changes to your repo, maybe I can help on that.

**Comment by merken** [comment]
> > Ok, progressing slowly, now I get **disk3 device is write locked** when trying to install Big Sur
> 
> Is that already with a GUI spinned up? Or still not past the verbose? Also can you push your changes to your repo, maybe I can help on that.

No GUI, still in verbose, endlessly....

I'm pushing now

**Comment by merken** [comment]
Updated the repo, added the current status

**Comment by merken** [comment]
@hacker1024 What is your BIOS version?

**Comment by mfischl** [comment]
@hacker1024 also what are your bios settings? I feel like this could be crucial also

**Comment by merken** [comment]
@mfischl I'm reaching the macOS installer! (Catalina)

Keyboard does not work..., WIFI seems to be working, I can connect to an open WIFI access point!

Pushing to my repo sometime later today, once the keyboard is fixed

**Comment by merken** [comment]
Hi, got it working using opencore 0.6.3 and Catalina:
https://github.com/merken/Inspiron7586

BIOS settings are in the readme

I'll experiment with never kext versions to see if I get bluetooth working, and fix audio

**Comment by mfischl** [comment]
> Hi, got it working using opencore 0.6.3 and Catalina:
> https://github.com/merken/Inspiron7586
> 
> BIOS settings are in the readme
> 
> I'll experiment with never kext versions to see if I get bluetooth working, and fix audio

Can confirm this working. I am currently installing 🎉  Did you always have bios version 1.7.1? I just upgraded and wonder if it also has to do with that.
@hacker1024 I wonder what was different to your setup?

**Comment by merken** [comment]
> > Hi, got it working using opencore 0.6.3 and Catalina:
> > https://github.com/merken/Inspiron7586
> > BIOS settings are in the readme
> > I'll experiment with never kext versions to see if I get bluetooth working, and fix audio
> 
> Can confirm this working. I am currently installing 🎉 Did you always have bios version 1.7.1? I just upgraded and wonder if it also has to do with that.
> @hacker1024 I wonder what was different to your setup?

Yes my machine was on 1.7.1 since march, I dare not to upgrade to 1.8.0... but I figured out that the CFG LOCK is the same in 1.7.1 and 1.8.0 so it should work on both...

Are you installing Big Sur ?

Also, after the verbose. It takes about 2-3 minutes for anything to show up...black screen for minutes and after a while the display functions normally... This is the same when you boot the machine after install... Still trying to figure out what6 the cause of it

**Comment by mfischl** [comment]
Alright, successfully installed and usable 🎉 
No, I installed Catalina.

I have the same issue with the black screen. On the installation process, the screen reader started on its on, hinting that everything was loaded already but the graphics didn't yet come on. Maybe something with the order of kexts you mentioned?

If you want I can also open an issue on your repo with what works and what doesn't for me?

**Comment by hacker1024** [comment]
I'm on 1.8.0. I have no idea why my config seems broken on your machines...

@merken My HDMI port works BTW, it's connected to the IGPU. I just need to plug it in _before_ booting.

**Comment by merken** [comment]
Now I'm on 1.8.0 too, the only difference is that I'm on Catalina...

After minutes the screen comes up, Not sure if its a backlight issue... Connecting a HDMI monitor via the USB C port allows me to log in, but the main laptop panel remains dark until minutes after boot...

Any ideas?

**Comment by hacker1024** [comment]
@merken Are you sure you have the required SSDT-PLNFCFL.aml ACPI file? It's required for proper backlight functionality on Coffee Lake (which is our Whiskey Lake generation's closest popular relative, and of which most things apply to Whiskey Lake as well).

**Comment by hacker1024** [comment]
I've just pushed some changes, including some GPU configuration changes. They may help.

**Comment by mfischl** [comment]
Ha, neat! I will try that when I have time. Your config is still for Big Sur right? Any chance that same thing will work with Catalina also?

**Comment by merken** [comment]
> SSDT-PLNFCFL.aml

Sorry, I tried this with no luck... Also updated kexts to latest, no change

**Comment by merken** [comment]
@hacker1024 You may close this issue, I've found a fix and will take this further on my repo: https://github.com/merken/Inspiron7586

Thanks for your work and support!

**Comment by hacker1024** [comment]
That's great to hear.
I'm perplexed at how I don't need the patch and you do - we have the same machine, after all... Interesting.

**Comment by hacker1024** [comment]
I got a dead pixel on my display, and Dell upgraded me to 4K for free. Now I'm getting the problem reported here! Mystery solved, I guess.

@merken @mfischl, on another note, how's the response time on your panels? It's noticeably bad compared to my old 1080p panel, especially when I move a white-bordered cursor on a black background.

**Comment by mfischl** [comment]
@hacker1024 not really to be honest… Everything was bliss as far as I could tell.

Did you manage to also solve that issue? I layed my Dell to rest for some months now and I am inclined to try your repo again since you seem to have solved the sleep issue also. Tell me if you need some help debugging/trial and errorring this.

**Comment by hacker1024** [comment]
@mfischl Turns out I just needed one WhateverGreen option that @merken was already using:

```
<key>enable-max-pixel-clock-override</key>
<data>AQAAAA==</data>
```

I've pushed this in [this commit](https://github.com/hacker1024/Dell-Inspiron-7586-Hackintosh/commit/e75c85ce2f2e5b05bdd31b2453e7761536e44809), which has been merged into my `monterey` branch (which should also work for Big Sur, by the way). It's a little messy because I removed useless connector properties, but that option was all that was needed.

**Comment by mfischl** [comment]
@hacker1024 Yes, seems like that worked, great! Seems like I still have the sleep issue though. But I also have to add that I only tried tour version off a USB, is that something that might influence that? But I guess bot since waking up from sleep won't read the EFI at all

**Comment by hacker1024** [comment]
@mfischl Which sleep issue exactly?

**Comment by mfischl** [comment]
@hacker1024 Well, when I close the lid, wait for a minute and reopen, the keyboard lights go on for a second and then it crashes without ever turning on the screen, and the immediately reboots

**Comment by hacker1024** [comment]
@mfischl I had that issue before configuring power management. Perhaps that's your problem?

**Comment by mfischl** [comment]
@hacker1024 Ah, I thought because you striked it through in the readme its not necessary anymore, its this one right? https://dortania.github.io/OpenCore-Post-Install/universal/pm.html#using-cpu-friend I'll try that next, thanks!

**Comment by hacker1024** [comment]
> I've pushed this in [this commit](https://github.com/hacker1024/Dell-Inspiron-7586-Hackintosh/commit/e75c85ce2f2e5b05bdd31b2453e7761536e44809), which has been merged into my monterey branch (which should also work for Big Sur, by the way). It's a little messy because I removed useless connector properties, but that option was all that was needed.

Oops - turns out I removed important LSPCON properties in that commit, preventing me from solving an annoying HDMI hot-plugging problem for a pretty long time...

That's fixed now. The IGPU device ID has also been changed to better represent the UHD 620, and the framebuffer ID has been tweaked as well to align with the WhateverGreen manual's recommended values.
